import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Header from "@/components/common/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
   const authToken = cookieStore.get('authToken')?.value;

   if(!authToken || authToken === 'undefined') {
    redirect('/');
   }

  return (
    <div className="flex flex-col">
      <Header />
      {children}
    </div>
  );
}