import { CartItem } from "@/stores/useCart";

export const cartItens: CartItem[] = [
    { name: 'Banana', price: 1.99, quantity: 1 },
    { name: 'Apple', price: 2.49, quantity: 1 },
    { name: 'Orange', price: 1.79, quantity: 1 },
    { name: 'Grapes', price: 3.99, quantity: 1 },
    { name: 'Strawberry', price: 4.99, quantity: 1 },
    { name: 'Watermelon', price: 5.99, quantity: 1 },
    { name: 'Pineapple', price: 3.49, quantity: 1 },
    { name: 'Mango', price: 2.99, quantity: 1 },
    { name: 'Blueberry', price: 6.99, quantity: 1 },
    { name: 'Kiwi', price: 1.49, quantity: 1 },
    { name: 'Papaya', price: 3.29, quantity: 1 },
    { name: 'Peach', price: 4.49, quantity: 1 },
    { name: 'Pear', price: 2.79, quantity: 1 },
    { name: 'Plum', price: 3.19, quantity: 1 },
    { name: 'Lemon', price: 1.29, quantity: 1 },
    { name: 'Lime', price: 1.39, quantity: 1 },
    { name: 'Coconut', price: 4.29, quantity: 1 },
    { name: 'Avocado', price: 5.49, quantity: 1 },
    { name: 'Guava', price: 3.79, quantity: 1 },
    { name: 'Passion Fruit', price: 4.59, quantity: 1 },
    { name: 'Tangerine', price: 2.19, quantity: 1 },
    { name: 'Cherry', price: 7.99, quantity: 1 },
    { name: 'Raspberry', price: 8.49, quantity: 1 },
    { name: 'Blackberry', price: 7.49, quantity: 1 },
    { name: 'Pomegranate', price: 6.49, quantity: 1 },
    { name: 'Fig', price: 5.79, quantity: 1 },
    { name: 'Apricot', price: 4.19, quantity: 1 },
    { name: 'Melon', price: 5.29, quantity: 1 },
    { name: 'Cantaloupe', price: 4.89, quantity: 1 },
    { name: 'Persimmon', price: 3.89, quantity: 1 },

    { name: 'Carrot', price: 2.29, quantity: 1 },
    { name: 'Potato', price: 3.49, quantity: 1 },
    { name: 'Tomato', price: 4.29, quantity: 1 },
    { name: 'Onion', price: 2.99, quantity: 1 },
    { name: 'Garlic', price: 1.89, quantity: 1 },
    { name: 'Lettuce', price: 2.49, quantity: 1 },
    { name: 'Cabbage', price: 3.19, quantity: 1 },
    { name: 'Broccoli', price: 4.79, quantity: 1 },
    { name: 'Cauliflower', price: 5.19, quantity: 1 },
    { name: 'Spinach', price: 3.99, quantity: 1 },
    { name: 'Cucumber', price: 2.39, quantity: 1 },
    { name: 'Zucchini', price: 3.59, quantity: 1 },
    { name: 'Eggplant', price: 3.29, quantity: 1 },
    { name: 'Bell Pepper', price: 4.49, quantity: 1 },
    { name: 'Corn', price: 2.79, quantity: 1 },
    { name: 'Peas', price: 3.89, quantity: 1 },
    { name: 'Green Beans', price: 4.19, quantity: 1 },
    { name: 'Beetroot', price: 2.69, quantity: 1 },
    { name: 'Pumpkin', price: 5.49, quantity: 1 },
    { name: 'Sweet Potato', price: 3.79, quantity: 1 },

    { name: 'Rice', price: 6.99, quantity: 1 },
    { name: 'Beans', price: 7.49, quantity: 1 },
    { name: 'Pasta', price: 4.99, quantity: 1 },
    { name: 'Flour', price: 5.29, quantity: 1 },
    { name: 'Sugar', price: 4.79, quantity: 1 },
    { name: 'Salt', price: 2.49, quantity: 1 },
    { name: 'Coffee', price: 12.99, quantity: 1 },
    { name: 'Tea', price: 8.49, quantity: 1 },
    { name: 'Cocoa Powder', price: 9.99, quantity: 1 },
    { name: 'Oatmeal', price: 7.99, quantity: 1 },
    { name: 'Corn Flakes', price: 10.49, quantity: 1 },
    { name: 'Granola', price: 11.99, quantity: 1 },
    { name: 'Bread', price: 6.49, quantity: 1 },
    { name: 'Toast', price: 5.99, quantity: 1 },
    { name: 'Crackers', price: 4.59, quantity: 1 },
    { name: 'Cookies', price: 6.79, quantity: 1 },
    { name: 'Chocolate', price: 5.49, quantity: 1 },
    { name: 'Peanut Butter', price: 9.49, quantity: 1 },
    { name: 'Jelly', price: 7.29, quantity: 1 },
    { name: 'Honey', price: 13.49, quantity: 1 },

    { name: 'Milk', price: 5.99, quantity: 1 },
    { name: 'Cheese', price: 14.99, quantity: 1 },
    { name: 'Butter', price: 8.99, quantity: 1 },
    { name: 'Yogurt', price: 4.49, quantity: 1 },
    { name: 'Cream Cheese', price: 7.99, quantity: 1 },
    { name: 'Eggs', price: 9.49, quantity: 1 },
    { name: 'Chicken Breast', price: 18.99, quantity: 1 },
    { name: 'Ground Beef', price: 22.49, quantity: 1 },
    { name: 'Beef Steak', price: 34.99, quantity: 1 },
    { name: 'Pork Chop', price: 19.99, quantity: 1 },
    { name: 'Sausage', price: 15.49, quantity: 1 },
    { name: 'Bacon', price: 17.99, quantity: 1 },
    { name: 'Ham', price: 16.49, quantity: 1 },
    { name: 'Tuna', price: 8.99, quantity: 1 },
    { name: 'Salmon', price: 29.99, quantity: 1 },
    { name: 'Shrimp', price: 27.49, quantity: 1 },
    { name: 'Fish Fillet', price: 21.99, quantity: 1 },
    { name: 'Mozzarella', price: 13.49, quantity: 1 },
    { name: 'Parmesan', price: 18.99, quantity: 1 },
    { name: 'Sour Cream', price: 6.49, quantity: 1 },

    { name: 'Orange Juice', price: 8.99, quantity: 1 },
    { name: 'Apple Juice', price: 7.99, quantity: 1 },
    { name: 'Grape Juice', price: 9.49, quantity: 1 },
    { name: 'Soda', price: 6.49, quantity: 1 },
    { name: 'Sparkling Water', price: 4.99, quantity: 1 },
    { name: 'Mineral Water', price: 2.99, quantity: 1 },
    { name: 'Coconut Water', price: 7.49, quantity: 1 },
    { name: 'Iced Tea', price: 5.99, quantity: 1 },
    { name: 'Energy Drink', price: 9.99, quantity: 1 },
    { name: 'Lemonade', price: 6.99, quantity: 1 },

    { name: 'Chips', price: 4.49, quantity: 1 },
    { name: 'Popcorn', price: 3.99, quantity: 1 },
    { name: 'Nuts', price: 8.49, quantity: 1 },
    { name: 'Trail Mix', price: 7.99, quantity: 1 },
    { name: 'Granola Bar', price: 2.99, quantity: 1 },
    { name: 'Candy', price: 5.49, quantity: 1 },
    { name: 'Chocolate Bar', price: 3.99, quantity: 1 },
    { name: 'Gum', price: 1.49, quantity: 1 },
    { name: 'Mints', price: 2.49, quantity: 1 },
    { name: 'Lollipop', price: 0.99, quantity: 1 },
    { name: 'Marshmallow', price: 3.29, quantity: 1 },
    { name: 'Jelly Beans', price: 4.19, quantity: 1 },
    { name: 'Caramel', price: 5.29, quantity: 1 },
    { name: 'Toffee', price: 6.19, quantity: 1 },
    { name: 'Fudge', price: 7.29, quantity: 1 },
    { name: 'Nougat', price: 8.39, quantity: 1 },
    { name: 'Ice Cream', price: 9.49, quantity: 1 },
    { name: 'Frozen Yogurt', price: 8.99, quantity: 1 },

    { name: 'Milk Chocolate', price: 5.99, quantity: 3 },
    { name: 'Dark Chocolate', price: 7.49, quantity: 2 },
    { name: 'White Chocolate', price: 6.99, quantity: 5 },
    { name: 'Chocolate Bar', price: 4.49, quantity: 4 },
    { name: 'Potato Chips', price: 8.99, quantity: 2 },
    { name: 'Tortilla Chips', price: 9.49, quantity: 3 },
    { name: 'Popcorn', price: 5.49, quantity: 6 },
    { name: 'Pretzels', price: 7.99, quantity: 2 },
    { name: 'Peanuts', price: 6.49, quantity: 5 },
    { name: 'Cashews', price: 14.99, quantity: 2 },

    { name: 'Almonds', price: 13.49, quantity: 3 },
    { name: 'Walnuts', price: 15.99, quantity: 1 },
    { name: 'Pistachios', price: 16.49, quantity: 4 },
    { name: 'Brazil Nuts', price: 12.99, quantity: 2 },
    { name: 'Raisins', price: 8.49, quantity: 5 },
    { name: 'Dried Apricots', price: 10.99, quantity: 3 },
    { name: 'Dried Cranberries', price: 11.49, quantity: 2 },
    { name: 'Trail Mix', price: 13.99, quantity: 4 },
    { name: 'Protein Bar', price: 8.99, quantity: 6 },
    { name: 'Cereal Bar', price: 5.99, quantity: 7 },

    { name: 'Vanilla Cookies', price: 6.49, quantity: 3 },
    { name: 'Oat Cookies', price: 7.29, quantity: 4 },
    { name: 'Butter Cookies', price: 8.49, quantity: 2 },
    { name: 'Wafer', price: 4.99, quantity: 8 },
    { name: 'Donut', price: 3.49, quantity: 5 },
    { name: 'Muffin', price: 4.99, quantity: 3 },
    { name: 'Croissant', price: 5.49, quantity: 2 },
    { name: 'Cupcake', price: 4.49, quantity: 6 },
    { name: 'Brownie', price: 5.99, quantity: 4 },
    { name: 'Cheesecake', price: 12.99, quantity: 1 },

    { name: 'Tomato Sauce', price: 4.99, quantity: 4 },
    { name: 'Ketchup', price: 6.49, quantity: 3 },
    { name: 'Mustard', price: 5.49, quantity: 2 },
    { name: 'Mayonnaise', price: 8.99, quantity: 5 },
    { name: 'Barbecue Sauce', price: 7.49, quantity: 2 },
    { name: 'Soy Sauce', price: 6.99, quantity: 4 },
    { name: 'Hot Sauce', price: 5.99, quantity: 3 },
    { name: 'Vinegar', price: 4.49, quantity: 6 },
    { name: 'Olive Oil', price: 24.99, quantity: 2 },
    { name: 'Vegetable Oil', price: 9.99, quantity: 3 },

    { name: 'Coconut Oil', price: 17.99, quantity: 1 },
    { name: 'Apple Cider Vinegar', price: 11.99, quantity: 2 },
    { name: 'Black Pepper', price: 5.99, quantity: 4 },
    { name: 'Paprika', price: 4.99, quantity: 3 },
    { name: 'Oregano', price: 3.99, quantity: 5 },
    { name: 'Basil', price: 4.49, quantity: 2 },
    { name: 'Cinnamon', price: 5.49, quantity: 6 },
    { name: 'Garlic Powder', price: 6.49, quantity: 3 },
    { name: 'Curry Powder', price: 7.99, quantity: 2 },
    { name: 'Chili Powder', price: 5.99, quantity: 4 },

    { name: 'Chicken Nuggets', price: 16.99, quantity: 2 },
    { name: 'French Fries', price: 12.49, quantity: 3 },
    { name: 'Frozen Pizza', price: 19.99, quantity: 1 },
    { name: 'Frozen Lasagna', price: 21.49, quantity: 2 },
    { name: 'Frozen Vegetables', price: 9.99, quantity: 4 },
    { name: 'Frozen Corn', price: 7.49, quantity: 3 },
    { name: 'Ice Cream', price: 14.99, quantity: 2 },
    { name: 'Popsicle', price: 8.99, quantity: 5 },
    { name: 'Frozen Berries', price: 13.99, quantity: 3 },
    { name: 'Frozen Burger', price: 18.49, quantity: 2 },

    { name: 'Mineral Water 500ml', price: 2.49, quantity: 10 },
    { name: 'Mineral Water 1L', price: 3.99, quantity: 8 },
    { name: 'Sparkling Water 500ml', price: 3.49, quantity: 6 },
    { name: 'Cola 350ml', price: 4.99, quantity: 7 },
    { name: 'Cola 2L', price: 9.99, quantity: 3 },
    { name: 'Orange Soda', price: 5.49, quantity: 4 },
    { name: 'Lemon Soda', price: 5.49, quantity: 5 },
    { name: 'Ginger Ale', price: 6.49, quantity: 2 },
    { name: 'Sports Drink', price: 7.99, quantity: 6 },
    { name: 'Iced Coffee', price: 8.49, quantity: 3 },

    { name: 'Green Tea', price: 9.99, quantity: 2 },
    { name: 'Black Tea', price: 8.99, quantity: 4 },
    { name: 'Chamomile Tea', price: 10.49, quantity: 3 },
    { name: 'Instant Coffee', price: 15.99, quantity: 2 },
    { name: 'Ground Coffee', price: 18.49, quantity: 5 },
    { name: 'Espresso Coffee', price: 22.99, quantity: 1 },
    { name: 'Hot Chocolate', price: 11.99, quantity: 4 },
    { name: 'Milk Powder', price: 16.49, quantity: 2 },
    { name: 'Condensed Milk', price: 6.99, quantity: 6 },
    { name: 'Coconut Milk', price: 8.49, quantity: 3 },

    { name: 'Toilet Paper', price: 18.99, quantity: 2 },
    { name: 'Paper Towels', price: 12.99, quantity: 3 },
    { name: 'Napkins', price: 7.49, quantity: 5 },
    { name: 'Dish Soap', price: 4.99, quantity: 4 },
    { name: 'Laundry Detergent', price: 15.99, quantity: 2 },
    { name: 'Fabric Softener', price: 13.49, quantity: 3 },
    { name: 'Glass Cleaner', price: 9.99, quantity: 2 },
    { name: 'Floor Cleaner', price: 11.49, quantity: 4 },
    { name: 'Bleach', price: 6.49, quantity: 5 },
    { name: 'Disinfectant', price: 10.99, quantity: 3 },

    { name: 'Toothpaste', price: 7.99, quantity: 2 },
    { name: 'Toothbrush', price: 6.49, quantity: 4 },
    { name: 'Shampoo', price: 14.99, quantity: 2 },
    { name: 'Conditioner', price: 15.49, quantity: 3 },
    { name: 'Body Soap', price: 5.99, quantity: 6 },
    { name: 'Liquid Soap', price: 8.49, quantity: 4 },
    { name: 'Deodorant', price: 11.99, quantity: 2 },
    { name: 'Body Lotion', price: 13.99, quantity: 3 },
    { name: 'Sunscreen', price: 24.99, quantity: 1 },
    { name: 'Hand Sanitizer', price: 6.99, quantity: 5 },

    { name: 'Shaving Cream', price: 9.49, quantity: 2 },
    { name: 'Razor', price: 12.99, quantity: 3 },
    { name: 'Aftershave', price: 14.49, quantity: 2 },
    { name: 'Hair Gel', price: 11.99, quantity: 4 },
    { name: 'Hair Spray', price: 13.49, quantity: 3 },
    { name: 'Hair Mousse', price: 10.99, quantity: 2 },
    { name: 'Hair Wax', price: 12.49, quantity: 4 },
    { name: 'Hair Pomade', price: 14.99, quantity: 3 },
    { name: 'Hair Serum', price: 16.49, quantity: 2 },
    { name: 'Hair Oil', price: 18.99, quantity: 1 },
    { name: 'Hair Mask', price: 19.99, quantity: 2 },
    { name: 'Hair Conditioner', price: 15.49, quantity: 3 },
    { name: 'Hair Shampoo', price: 14.99, quantity: 4 },
    { name: 'Hair Treatment', price: 21.99, quantity: 2 },
    { name: 'Hair Color', price: 24.99, quantity: 1 },
    { name: 'Hair Bleach', price: 29.99, quantity: 1 },
];